# Generated by Django 3.2.6 on 2021-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=100)),
                ('emp_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employeedetails',
            },
        ),
    ]
