# Generated by Django 3.2.6 on 2021-08-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gendertable',
            },
        ),
    ]
