# Generated by Django 3.2.6 on 2021-08-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
